[Fix] implementation bugs
brille/brille pull request #55
Opened 2021-11-03 15:24 UTC by g5t

- Extracting Array2 elements should only require a vector-like list of
  elements not necessarily a (N,1) Array2.
  The DebugPrinter brille::printer was not singular, with multiple
  versions existing in the compiled code -- this prevented using the
  datetime() return value to control timing/printing information in
  triangulation_layers.hpp.
  The layer-connection timing information should not always be printed.
- Array2::extract now takes (1,N) or (N,1) arrays of indexes. Fixing
  this highlighed a problem with Array2::is, which has also been fixed.
  There is now a single global brille::printer, declared `extern` in
  debug.hpp and constructed in debug.cpp (instead of declared `static`
  and constructed in debug.hpp).
  The layer-connection timing information is only printed if
  brille::printer.datetime() is true (which is false by default)
- Changing the behaviour of Array2::extract and Array2::is might effect
  other parts of brille. Testing should identify this if it happens.

Merging this PR should close #54

2021-11-03 17:28 UTC, rebeccafair requested changes
I have tested this and it fixes the issue,~although I then get a `RuntimeError: The point was not located!` when calling `grid.ir_interpolate_at(qpts)`. Some q-points that cause this error are `[0.35869565, 0.35869565, 0.7173913 ]`, `[0.5  , 0.25 , 0.75 ]`, `[0.5  , 0.225, 0.725]`, `[0.5, 0.15, 0.65]`, this may be a separate issue.~

I'm not so familiar with Brille (or C++ for that matter) but I'll try my best to review, although I have lots of questions...

- What is the difference between Array and Array2? They both look very similar
- Is simply allowing Array2 to take (N, 1) and (1, N) input fixing the issue or obscuring other issues? Why was the calling function not passing the correctly shaped array in in the first place?

It may be I don't understand properly and this is the best solution, just thought I'd ask the question...

2021-11-03 17:28 UTC, rebeccafair commented on src/array2.tpp
> +  // return out;
Do we need these commented lines?

2021-11-04 16:08 UTC, g5t commented on src/array2.tpp
> +  // return out;
We do not. In fact, this method should be split into two clearly-defined methods instead.

2021-11-04 16:23 UTC, g5t commented
- The `ir_interpolate_at` misses are (probably) a separate issue -- are they also for the `La2Zr2O7.castep_bin` system?

- `Array` and `Array2` are indeed very similar. My first attempt at memory-sharing used exclusively `Array` objects which are `N`-dimensional shared-memory arrays, but the performance was not particularly great (I think due to the use of `std::vector`s to hold array shapes, strides, indexes, etc.).
The `Array` class lives on to support higher-than-two-dimensional input to the grid `fill` objects, and in case the poor performance can be improved by switching to, e.g., `std::array` containers for the various properties, while still allowing for `N`-D arrays.
`Array2` is the 2-D specialization of `Array`, and is the direct replacement for the old `ArrayVector` class (which did not share memory). It was copied from `Array`, with modifications as necessary as they arise.

- I think that allowing `Array2::extract(Array2<int>)` to take either `(1, N)` or `(N, 1)` input is fine, since in either case we're specifying a list of indexes to pull out of the object.

2021-11-05 09:03 UTC, rebeccafair commented
> * The `ir_interpolate_at` misses are (probably) a separate issue -- are they also for the `La2Zr2O7.castep_bin` system?

Yes, if you add `ir_interpolate_at` for those q-points at the end of the script in #54 you get that error

> * `Array` and `Array2` are indeed very similar. My first attempt at memory-sharing used exclusively `Array` objects which are `N`-dimensional shared-memory arrays, but the performance was not particularly great (I think due to the use of `std::vector`s to hold array shapes, strides, indexes, etc.).
>   The `Array` class lives on to support higher-than-two-dimensional input to the grid `fill` objects, and in case the poor performance can be improved by switching to, e.g., `std::array` containers for the various properties, while still allowing for `N`-D arrays.
>   `Array2` is the 2-D specialization of `Array`, and is the direct replacement for the old `ArrayVector` class (which did not share memory). It was copied from `Array`, with modifications as necessary as they arise.

Ah I see, thanks for the explanation :)

> * I think that allowing `Array2::extract(Array2<int>)` to take either `(1, N)` or `(N, 1)` input is fine, since in either case we're specifying a list of indexes to pull out of the object.

Ok, but why were we only seeing this error with LZO? Surely any material will use the same axes order so we should've seen it with all materials or none of them? But again I don't really understand how it all works so maybe there's a good reason...

2021-11-05 12:31 UTC, g5t commented
> Ok, but why were we only seeing this error with LZO? 

The same error is raised for both the Niobium and Quartz CASTEP files on my machine. I don't know why/when you've haven't seen it with other systems.

If you can point me in the right direction, I can look into why the error is not raised in some cases.

2021-11-05 14:14 UTC, rebeccafair commented
> > Ok, but why were we only seeing this error with LZO?
> 
> The same error is raised for both the Niobium and Quartz CASTEP files on my machine. I don't know why/when you've haven't seen it with other systems.
> 
> If you can point me in the right direction, I can look into why the error is not raised in some cases.

Now that you mention it I am actually getting that same error with other systems too. Don't know why I suddenly thought it was only LZO, sorry!

2021-11-05 14:15 UTC, rebeccafair approved these changes

2021-11-05 14:42 UTC, merged