Require keyword arguments for symmetry operations and atom basis information
brille/brille pull request #81
Opened 2022-07-21 09:51 UTC by g5t

Along with other improvements with the move to `v0.6.0` this PR finishes implementing the suggestions in #42.

Most notably, by wrapping `brille._brille.Lattice` initialization in Python a user now must provide symmetry operation and/or atom basis information via keyword arguments. The provided keyword value can be either a fully-constructed `brille._brille.[X]` object *or* an appropriate tuple used to construct and initialize such an object. For `Lattice = brille.Lattice`, the supported keyword values are:
- `Lattice(..., symmetry=Symmetry_object, ...)` or `Lattice(..., symmetry=(rotations, translations), ...)`
- `Lattice(..., basis=Basis_object, ...)` or `Lattice(..., basis=(atom_positions, atom_type_indexes), ...)`

Information about the crystal system can be provided as before, as one or two position-based argument string(s), *or* as a keyword argument `spacegroup` which is either one string or a tuple of two strings. As before a single string should be one of:
- Hall symbol, encoding the generators of the symmetry operations of the crystal system
- Hermann-Mauguin symbol, as from the International Tables of Crystallography
- The generators or symmetry operations of the crystal system encoded in CIF xyz format
And two strings should be a Hermann-Mauguin symbol plus its origin shifting, axis orientation, etc., 'choice', as appropriate.

2022-07-22 22:10 UTC, mducle approved these changes
Looks good... just had a few nitpicky comments...

(I haven't reviewed `subscript.hpp` because I have no idea what it's meant to do!)

Edit: I agree with the new simplified syntax where the single value `a, b, c, alpha, beta, gamma` syntax is removed.

2022-07-22 22:10 UTC, mducle commented on brille/utils.py
> +                                               for pname in ['a', 'b', 'c', 'alpha', 'beta', 'gamma', 'lens', 'angs'])
Since you've simplified the `Lattice` constructor to not allow single values, should we still support those in this helper `create_bz` function? (Although removing those now is more work and might break some scripts, it might make it easier to maintain in future?) 

On the other, should `create_bz` also now handle `basis` or `symmetry` as keyword arguments?

(I don't have any views either way ;)

2022-07-25 10:32 UTC, rebeccafair requested changes
This will definitely make things nicer to use from Python! Just a few comments

2022-07-25 10:32 UTC, rebeccafair commented on brille/lattice.py
> +    if symmetry is None and basis is None:
The if logic here is slightly hard to follow maybe it could be rearranged to be clearer?

e.g. maybe get the errors out of the way first?
```
if symmetry provided and spacegroup provided
# error
if basis and not symmetry provided and not spacegroup provided
# error
```
Also here we're allowing a spacegroup to be provided without a basis, is that ok?

Are all these code paths tested?

2022-07-25 10:32 UTC, rebeccafair commented on brille/lattice.py
> +    _Lattice, _Symmetry, _Basis = [getattr(_brille, x) for x in ('Lattice', 'Symmetry', 'Basis')]
I'm not sure I like testing workarounds being in the distributed package, but I guess unless wheels are built and installed before testing, there's no other option?

2022-07-25 10:32 UTC, rebeccafair commented on brille/utils.py
> +                                               for pname in ['a', 'b', 'c', 'alpha', 'beta', 'gamma', 'lens', 'angs'])
I think `create_bz` should maybe even just take `Lattice` as a required positional argument, to avoid a lot of the cell/spacegroup/symmetry logic that is repeated here. But would that make this helper function obsolete?

I think we should lean towards giving users fewer ways of doing the same things as it's easier to maintain but that's just me...

2022-07-26 13:03 UTC, g5t commented on brille/lattice.py
> +        if len(args) > 2 and isinstance(args[-1], str) and isinstance(args[-2], str):
@rebeccafair also suggested removing non-keyword spacegroup information, so I'll capitulate.

I'll add the same into the docstring, but for completeness:
```
Valid syntax for (Hermann-Mauguin, choice) input depends on the spacegroup but is generally one of:
    a single letter ('a', 'b', or 'c') with possible prepended '-', denoting unique-axis choice
    a single digit ('1', '2', or '3'), denoting origin choice
    a letter and digit, denoting unique-axis and origin choice
    a permutation of 'abc' with possible '-' before one of the letters, denoting axis permutation
    or 'R' or 'H' for trigonal systems with Rhombohedral or Hexagonal lattice settings, respectively.
Acceptable values are contained in the C++ source code in the seventh column of the table
https://github.com/brille/brille/blob/eecb4cb28227665908793abc47e88c69518c09fc/src/spg_database.cpp#L63-L610
with each line representing one spacegroup with values, in order, defined by the class signature at
https://github.com/brille/brille/blob/eecb4cb28227665908793abc47e88c69518c09fc/src/spg_database.hpp#L80-L91
These values come from spglib, which likely obtained them from Seto's now defunct Home Page,
https://web.archive.org/web/20210621195003/http://pmsl.planet.sci.kobe-u.ac.jp/~seto/?page_id=37&lang=en
```

2022-07-26 13:29 UTC, g5t commented on brille/utils.py
> +                                               for pname in ['a', 'b', 'c', 'alpha', 'beta', 'gamma', 'lens', 'angs'])
I would be happy to remove the scalar input parsing from `create_bz`, I've left it at present to avoid breaking possible use cases.
Changing `create_bz` to require a pre-constructed `brille._brille.Lattice` is fine for me, but may be a step too far for others? Ignoring the scalar value constructors, the syntax would change from
```python
# positional argument(s) for lattice parameters
bz = create_bz(lengths, angles, **lattice_keywords, **bz_keywords)
bz = create_bz(vectors, **lattice_keywords, **bz_keywords)
# equivalent keyword arguments
bz = create_bz(lens=lengths, angs=angles, **lattice_keywords, **bz_keywords)
bz = create_bz(lattice_vectors=vectors, **lattice_keywords, **bz_keywords)
```
to
```python
bz = create_bz(Lattice(lengths, angles, **lattice_keywords), **bz_keywords)
bz = create_bz(Lattice(vectors, **lattice_keywords), **bz_keywords)
```
where the keyword-argument variants will no longer work since the signature of the `Lattice` wrapper is
`def Lattice(*args, **kwargs)`. Keeping both the position and keyword argument syntaxes requires functionality like `create_bz`, though I'm not sure if both versions are used.

Does anyone use `create_bz(**only_keywords)`?

2022-07-26 13:32 UTC, g5t commented on brille/lattice.py
> +    """
I can add the current crop of keyword arguments to the docstring, but I was hoping to avoid copying signatures from the pybind11 wrappers -- especially in case those signatures change in the future.
I'll look into providing links in the online documentation.

2022-07-26 13:33 UTC, g5t commented on brille/lattice.py
> +            The three basis vector lengths in angstrom for real lattice, or inverse angstrom for reciprocal lattices
Via one of the keyword arguments not documented here, of course :sweat:

2022-07-26 13:35 UTC, g5t commented on brille/lattice.py
> +        # look for a string (or two!) on the end of the position arguments
Good suggestion, this is changed to keyword-only and will be pushed shortly.

2022-07-26 13:40 UTC, g5t commented on brille/lattice.py
> +    args:
Avoiding nonsensical cases is a good idea. I'm willing to give the single positional argument idea a chance. I've tentatively gone with `values` instead of `cell`, since I think the latter has a specific meaning for `spglib` and `euphonic` users.

Should I make the single argument positional-only? E.g., `def Lattice(values, /, **kwargs)`.
Then a user can't provide the argument as a keyword, so its name is less important?

2022-07-26 13:46 UTC, g5t commented on brille/lattice.py
> +    if symmetry is None and basis is None:
:+1:  Thanks for the suggestion, I'll implement it.

User provided spacegroup string(s) or symmetry operations without an atom basis are fine but a basis without either is not.

2022-07-26 13:46 UTC, rebeccafair commented on brille/lattice.py
> +    args:
Yeah, I think if we _always_ need an argument, it should be positional, good point about its name being less important in that case.

2022-07-26 14:24 UTC, rebeccafair commented on brille/lattice.py
> +    _Lattice, _Symmetry, _Basis = [getattr(_brille, x) for x in ('Lattice', 'Symmetry', 'Basis')]
I've never used it, but could [\_\_debug\_\_](https://docs.python.org/3/library/constants.html#debug__) be helpful here? It looks like you can run Python with the [-O](https://docs.python.org/3/using/cmdline.html#cmdoption-o) option to run any code in a `__debug__` section. Or have you tried an editable install with `pip install -e`? Sorry if these suggestions are no good, I'm not so familiar with how the tests are run.

I don't imagine the try/catch will have an effect on performance, but I worry that if a user doesn't have `brille` installed properly, it could trigger the `catch` and hide what the real problem is.

2022-07-26 14:41 UTC, g5t commented on brille/lattice.py
> +    _Lattice, _Symmetry, _Basis = [getattr(_brille, x) for x in ('Lattice', 'Symmetry', 'Basis')]
I'd guess `pip install -e` is similar to the `develop` option for `setup.py` -- this is a really good way to avoid re-building the compiled module for every change to the Python code, but the package is still installed (via an 'egg link') for the current Python interpreter.
If that interpreter is inside of a development-specific virtual environment ([Virualenv](https://virtualenv.pypa.io/en/latest/), Conda-like, [pipenv](https://pipenv.pypa.io/en/latest/), [poetry](https://python-poetry.org/), or similar) there's no problem. But if a developer (me) accidentally installs the development module for, e.g., the system interpreter, there is the possiblity to unintentionally use the development instead of stable version of the module elsewhere.

I'll try to think of a simpler way (e.g., something I can't forget to do when building `brille`) to avoid this while also not putting an unnecessary `try/except` block in the distributed module.

2022-07-26 15:51 UTC, g5t commented on brille/lattice.py
> +    args:
Position-only arguments are not available in Python 3.6 and 3.7 so I _can not_ make this so strict until the minimum supported version of Python can move to 3.8.

Python 3.6 is past EOL and 3.7 will pass the same milestone in 11 months. Does PACE still plan to support 3.6 and 3.7?

2022-07-26 16:05 UTC, rebeccafair commented on brille/lattice.py
> +    args:
Sorry, I didn't really mean positional argument, I meant required! So the Python versioning shouldn't be an issue (sorry, it's bad of me to muddy those 2 things).

But FYI Euphonic will stop supporting Python 3.6 as of Euphonic 1.0, and from now on we'll probably attempt to roughly follow whatever Python versions have official support (unless there's a reason not to).

2022-08-03 13:15 UTC, g5t commented on brille/lattice.py
> +    """
This is done in the docstring but other documentation changes are needed, so #84 will pull the changes into the built HTML file.

2022-08-03 13:17 UTC, g5t commented on brille/lattice.py
> +    _Lattice, _Symmetry, _Basis = [getattr(_brille, x) for x in ('Lattice', 'Symmetry', 'Basis')]
The `try/except` blocks are now gone and developer tools have been added to build and test the CTest and python tests in a PyPA manylinux image.

2022-08-03 13:21 UTC, merged